services:
  - type: web
    name: trip-logger-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn --bind 0.0.0.0:$PORT core.wsgi:application
    envVars:
      - key: ORS_API_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: trip-logger-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: trip-logger-redis
          property: connectionString

  - type: redis
    name: trip-logger-redis
    plan: free

  - type: pserv
    name: trip-logger-db
    env: postgresql
    plan: free
    region: oregon
