services:
  - type: web
    name: trip-logger-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT core.wsgi:application
    envVars:
      - key: RENDER
        value: true
      - key: ORS_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: trip-logger-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: trip-logger-redis
          property: connectionString

databases:
  - name: trip-logger-db
    databaseName: trip_logger
    user: trip_logger_user

services:
  - type: redis
    name: trip-logger-redis
    maxmemoryPolicy: allkeys-lru
