# Generated by Django 5.2.6 on 2025-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='start_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
