# Generated by Django 5.2.6 on 2025-09-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_logentry_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
